apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-static-site
spec:
  replicas: 2 # Run 2 copies for high availability
  selector:
    matchLabels:
      app: my-static-site
  template:
    metadata:
      labels:
        app: my-static-site
    spec:
      containers:
      - name: web-server
        # This placeholder will be replaced by the pipeline
        image: ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-static-site-service
spec:
  type: LoadBalancer # Requests a public IP from AWS
  selector:
    app: my-static-site
  ports:
    - protocol: TCP
      port: 80 # External port
      targetPort: 80 # Container port
